services:
  dashboard:
    build: .
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./public:/app/public
      - ./server.js:/app/server.js
    environment:
      - PORT=3000
      - WIDTH=800
      - HEIGHT=480
      - TZ=Europe/Helsinki
      - GOOGLE_KEY_FILE=/app/google-service-account.json
      - GOOGLE_CALENDAR_ID=
      - GOOGLE_DRIVE_FOLDER_ID=
